version: '3'

services:
  client:
    container_name: client
    restart: always
    external_links:
      - api
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    container_name: api
    restart: always
    external_links:
      - mongo
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
    volumes:
      - /app/node_modules
      - ./api:/app
  db:
    container_name: db
    restart: always
    image: mongo
    ports:
      - '27017:27017'
