export const statusOptions = [
  { label: '', value: '' },
  { label: 'Student', value: 'Student' },
  { label: 'Jr. Developer', value: 'Jr. Developer' },
  { label: 'Experience Developer', value: 'Experience Developer' },
  { label: 'Sinior Developer', value: 'Sinior Developer' },
  { label: 'Project Manager', value: 'Project Manager' },
  { label: 'UX Designer', value: 'UX Designer' },
  { label: 'Designer', value: 'Designer' },
  { label: 'Instructor', value: 'Instructor' },
];

export const locationOptions = [
  { label: '', value: '' },
  { label: 'Adjuntas', value: 'Adjuntas' },
  { label: 'Aguada', value: 'Aguada' },
  { label: 'Aguadilla', value: 'Aguadilla' },
  { label: 'Aguas Buenas', value: 'Aguas Buenas' },
  { label: 'Aibonito', value: 'Aibonito' },
  { label: 'Arecibo', value: 'Arecibo' },
  { label: 'Arroyo', value: 'Arroyo' },
  { label: 'Añasco', value: 'Añasco' },
  { label: 'Barceloneta', value: 'Barceloneta' },
  { label: 'Barranquitas', value: 'Barranquitas' },
  { label: 'Bayamón', value: 'Bayamón' },
  { label: 'Cabo Rojo', value: 'Cabo Rojo' },
  { label: 'Caguas', value: 'Caguas' },
  { label: 'Camuy', value: 'Camuy' },
  { label: 'Canóvanas', value: 'Canóvanas' },
  { label: 'Carolina', value: 'Carolina' },
  { label: 'Cataño', value: 'Cataño' },
  { label: 'Cayey', value: 'Cayey' },
  { label: 'Ceiba', value: 'Ceiba' },
  { label: 'Ciales', value: 'Ciales' },
  { label: 'Cidra', value: 'Cidra' },
  { label: 'Coamo', value: 'Coamo' },
  { label: 'Comerío', value: 'Comerío' },
  { label: 'Corozal', value: 'Corozal' },
  { label: 'Culebra', value: 'Culebra' },
  { label: 'Dorado', value: 'Dorado' },
  { label: 'Fajardo', value: 'Fajardo' },
  { label: 'Florida', value: 'Florida' },
  { label: 'Guayama', value: 'Guayama' },
  { label: 'Guayanilla', value: 'Guayanilla' },
  { label: 'Guaynabo', value: 'Guaynabo' },
  { label: 'Gurabo', value: 'Gurabo' },
  { label: 'Guánica', value: 'Guánica' },
  { label: 'Hatillo', value: 'Hatillo' },
  { label: 'Hormigueros', value: 'Hormigueros' },
  { label: 'Humacao', value: 'Humacao' },
  { label: 'Isabela', value: 'Isabela' },
  { label: 'Jayuya', value: 'Jayuya' },
  { label: 'Juana Díaz', value: 'Juana Díaz' },
  { label: 'Juncos', value: 'Juncos' },
  { label: 'Lajas', value: 'Lajas' },
  { label: 'Lares', value: 'Lares' },
  { label: 'Las Marías', value: 'Las Marías' },
  { label: 'Las Piedras', value: 'Las Piedras' },
  { label: 'Loíza', value: 'Loíza' },
  { label: 'Luquillo', value: 'Luquillo' },
  { label: 'Manatí', value: 'Manatí' },
  { label: 'Maricao', value: 'Maricao' },
  { label: 'Maunabo', value: 'Maunabo' },
  { label: 'Mayagüez', value: 'Mayagüez' },
  { label: 'Moca', value: 'Moca' },
  { label: 'Morovis', value: 'Morovis' },
  { label: 'Naguabo', value: 'Naguabo' },
  { label: 'Naranjito', value: 'Naranjito' },
  { label: 'Orocovis', value: 'Orocovis' },
  { label: 'Patillas', value: 'Patillas' },
  { label: 'Peñuelas', value: 'Peñuelas' },
  { label: 'Ponce', value: 'Ponce' },
  { label: 'Quebradillas', value: 'Quebradillas' },
  { label: 'Rincón', value: 'Rincón' },
  { label: 'Rio Grande', value: 'Rio Grande' },
  { label: 'Sabana Grande', value: 'Sabana Grande' },
  { label: 'Salinas', value: 'Salinas' },
  { label: 'San Germán', value: 'San Germán' },
  { label: 'San Juan', value: 'San Juan' },
  { label: 'San Lorenzo', value: 'San Lorenzo' },
  { label: 'San Sebastián', value: 'San Sebastián' },
  { label: 'Santa Isabel', value: 'Santa Isabel' },
  { label: 'Toa Alta', value: 'Toa Alta' },
  { label: 'Toa Baja', value: 'Toa Baja' },
  { label: 'Trujillo Alto', value: 'Trujillo Alto' },
  { label: 'Utuado', value: 'Utuado' },
  { label: 'Vega Alta', value: 'Vega Alta' },
  { label: 'Vega Baja', value: 'Vega Baja' },
  { label: 'Vieques', value: 'Vieques' },
  { label: 'Villalba', value: 'Villalba' },
  { label: 'Yabucoa', value: 'Yabucoa' },
  { label: 'Yauco', value: 'Yauco' },
];
